#!/bin/bash

if [ "$1" = "vatten" ]; then
	scale=$(awk "BEGIN { print (5/3) }")
elif [ "$1" = "ris" ]; then
	scale=$(awk "BEGIN { print (3/5) }")
fi

calc=$(awk "BEGIN { print ($2*$scale) }" )
if [ "$1" = "vatten" ];  then
	resultType="ris";
else
	resultType="vatten";
fi
echo -n "För $2 dl $1 krävs "
echo -n "$(tput setaf 2)"
# test printf
if [ ! $(printf "%.*f" 1 0.5 1>/dev/null 2>&1) ]; then calc=$(echo "$calc" | sed 's#\.#,#g'); fi
printf '%.*f' 1 $calc
echo "$(tput op) dl $resultType"
